### ISSUE TITLE
clang: error: no such file or directory: 'TIMEOUT_US=400000'

### ISSUE THREAD

**Issue by rustem-spb** [Tripouille/printfTester#11]
Hello! What can I do with this error?
OS Ubunta

**Comment by Chinimala** [comment]
Hello, please describe your problem. What did you do/try to do ? Screenshot ?

**Comment by rustem-spb** [comment]
I am sorry. My mistake!
I have named in Makefile NAME = ft_printf.a instead libftprintf.a
And got error 
clang: error: linker command failed with exit code 1 (use -v to see invocation)
then I wrongly added -v key and got message 
clang: error: no such file or directory: 'TIMEOUT_US=400000'
If I had better programming skills I'll make a tester patch to check the name of .a file)))

**Comment by Chinimala** [comment]
Well, you already found there was an error in your repo using this tester, it doesn't have to tell how to correct the mistakes !
Good luck at 42 :)
