### ISSUE TITLE
Bonus Part

### ISSUE THREAD

**Issue by Paragonb** [Tripouille/printfTester#12]
![image](https://user-images.githubusercontent.com/100392058/155637052-2e7fbc61-c033-4940-9788-4a93942ef454.png)

minus test : sub s - 1 & sub p 1 be tested with no minus.
Should I handle this case?
![image](https://user-images.githubusercontent.com/100392058/155637488-e0b9ffd4-5103-45b3-aeee-0f1750479355.png)

space test : sub s - I tested with printf(), it's show
![image](https://user-images.githubusercontent.com/100392058/155637981-2efa4f58-3be1-4baa-b830-e80ba6c47143.png)
 
Should I handle this case too?
![image](https://user-images.githubusercontent.com/100392058/155637752-8bc548d1-4bb4-42c8-95b0-12490f7d43fa.png)

**Comment by Chinimala** [comment]
Hello,
Seems like you don't have to handle this case, from what I read from the man.
However this tester isn't maintained anymore, and is only supposed to be a helping tool, it could have too many or not enough tests, those tests won't be removed. It's your call to look at the man, take your own decisions, and justify them at evaluation.
Have fun coding !
