### ISSUE TITLE
Doesn't test when a percent is followed by a non-flag char.

### ISSUE THREAD

**Issue by herbievine** [Tripouille/printfTester#19]
If you pass a percent sign followed by a flag which is illegal, the original `printf` prints both the percent sign and the following character, and so should `ft_printf`.

I hadn't considered this and found out by testing it manually.

Example:
```c
int main()
{
	printf("this is a test %w\n");
	ft_printf("this is a test %w\n");
	return (0);
}
```
stdout:
```
@herbievine ➜ /workspaces/42/ft_printf (main ✗) $ ./a.out 
this is a test %w
this is a test 
```

Just something to consider adding.

**Comment by Chinimala** [comment]
Issue closed (explained in associated PR)
