### ISSUE TITLE
make bonus error

### ISSUE THREAD

**Issue by jsmyb** [Tripouille/printfTester#2]
Testing of the bonus part is no longer working, and it shows that it's up to date.
<img width="785" alt="Screen Shot 2021-06-15 at 7 31 20 PM" src="https://user-images.githubusercontent.com/52875945/122081650-55402d80-ce10-11eb-8b70-fcbc43f2bbaa.png">

**Comment by Chinimala** [comment]
Hello,
Is the tester in your repo ?
Does YOUR makefile have a bonus rule ? (that can be made with "make bonus")
