### ISSUE TITLE
Hexadecimal tests passing in spite of mistake

### ISSUE THREAD

**Issue by nicolasgasco** [Tripouille/printfTester#4]
Hi! Great work as usual with these tests 👍
I found a small issue, which may not be an issue at all, but still...

When converting from decimal to hexadecimal, I have a condition to check if the remainder of the number to be converted is smaller than 10 (and therefore it must be 0-9) or bigger than 9 (there it must be A-F).
I made a mistake and wrote it like this:

```
if (hex % 16 <= 10)
    ft_putnbr(hex % 16, counter);
else
   *counter += write(1, &alpha[hex % 16 - 10], 1);
```
The <= in line 1 is wrong and I was getting e.g. 210 instead of 2A for 42 (the decimal). I noticed because the mix test was failing, but all the x/X ones were good. I haven't looked further into it, but I think that it would be as easy as adding a 42 in the x/X tests to flag this kind of error sooner.

Thanks!

**Comment by Tripouille** [comment]
Hi, Thank you for your feedback, can you do a pull request ?

**Comment by nicolasgasco** [comment]
Done! Hope it's fine.

**Comment by Tripouille** [comment]
Thanks !
