### ISSUE TITLE
String returns incorrect value with a big string

### ISSUE THREAD

**Issue by wwwwelton** [Tripouille/printfTester#9]
Moulinette killed my friend with a big string.

Test the return value with:
 `Mussum Ipsum, cacilds vidis litro abertis. Posuere libero varius. Nullam a nisl ut ante blandit hendrerit. Aenean sit amet nisi. Atirei o pau no gatis, per gatis num morreus. Copo furadis é disculpa de bebadis, arcu quam euismod magna. Si num tem leite então bota uma pinga aí cumpadi! Diuretics paradis num copo é motivis de denguis. Todo mundo vê os porris que eu tomo, mas ninguém vê os tombis que eu levo! Mais vale um bebadis conhecidiss, que um alcoolatra anonimis. Casamentiss faiz malandris se pirulitá. A ordem dos tratores não altera o pão duris. Nullam volutpat risus nec leo commodo, ut interdum diam laoreet. Sed non consequat odio. Per aumento de cachacis, eu reclamis. Nec orci ornare consequat. Praesent lacinia ultrices consectetur. Sed non ipsum felis.`
 
 Check the len of return;
![unknown](https://user-images.githubusercontent.com/38966653/141602712-6b6446dc-16b5-43a6-9610-5384b8e60dc9.png)
![unknown2](https://user-images.githubusercontent.com/38966653/141602713-ff72a86a-006d-4d90-9799-79e98fed5be7.png)

**Comment by VLN37** [comment]
Error occurs when the student returns the size of the written string into a function that returns a char. Example:
![image](https://user-images.githubusercontent.com/54167882/141651081-4852a8c1-890c-4f39-bd2a-f2cd88b26db5.png)

**Comment by Tripouille** [comment]
![](https://media0.giphy.com/media/tm44HjWBeTH8szFYXZ/giphy.gif)
